
AWSTemplateFormatVersion: 2010-09-09
Description: Kurves / Udacity - This template deploys a VPC

AWSTemplateFormatVersion: 2010-09-09
Description: kurves / Udacity - This template deploys a VPC
Resources:
kurvesVPC:
 Type: 'AWS::EC2::VPC'
 Properties:
   CidrBlock: 10.0.0.0/16
   EnableDnsHostnames: 'true'

Resources:
kurvesEC2Instance:
Type: "AWS::EC2::Instance"
Properties:
 ImageId: "ami-0ff8a91507f90f867"
 
Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPCID
